region: "us-east-1"

modules:
  vpc:
    vpc_name: "my-vpc"
    vpc_cidr: "10.0.0.0/16"

  subnet:
    vpc_id: "module.vpc.vpc_id"
    subnets:
      subnet-1:
        cidr: "10.0.1.0/24"
        az: "us-east-1a"
        public: true
      subnet-2:
        cidr: "10.0.2.0/24"
        az: "us-east-1b"
        public: false

  ec2:
    ami: "ami-052064a798f08f0d3"
    instance_type: "t2.micro"
    key_name: "EC2_Key"
    instance_name: "my-ec2"
    subnet_id: module.subnet.subnet_ids["subnet-1"]
    sg_id: "module.sg.sg_id"

  sg:
    vpc_id: "module.vpc.vpc_id"
    name: "main-sg"
    ingress_rules:
      - from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks: ["0.0.0.0/0"]
    egress_rules:
      - from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks: ["0.0.0.0/0"]