region: "us-east-1"

modules:
  vpc:
    vpc_name: "my-vpc2"
    vpc_cidr: "20.0.0.0/16"

  subnet:
    vpc_id: "module.vpc.vpc_id"
    subnets:
      subnet-1:
        cidr: "20.0.1.0/24"
        az: "us-east-1a"
        public: true
      subnet-2:
        cidr: "20.0.2.0/24"
        az: "us-east-1b"
        public: false